Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  
  #config.vm.network "public_network", ip: "110.110.0.1", bridge: "wlo1"
  
  config.vm.synced_folder "../infra-services", "/infra-services", create: true
  
  config.vm.network "forwarded_port", guest: 8761, host: 18761
  config.vm.network "forwarded_port", guest: 8888, host: 18888
  config.vm.network :forwarded_port, guest: 15672, host: 25672
  config.vm.network :forwarded_port, guest: 9042, host: 19042
 

  config.vm.provider "virtualbox" do |v|
    v.memory = 3000
    v.cpus = 2
  end
  
  config.vm.provision "docker" do |d|
    d.build_image "--tag=java /vagrant/java"
    d.build_image "--tag=eureka /vagrant/eureka"
    d.build_image "--tag=config-server /vagrant/config-server"
  end    

  config.vm.provision "docker", run: "always" do |d|
    
    d.run "eureka", args: "-p 8761:8761 -v /infra-services:/infra-services"
    
    d.run "config-server", args: "-p 8888:8888 -v /infra-services:/infra-services --link eureka:eureka"
   
    d.pull_images "rabbitmq:3-management"
    
    d.run "rabbitmq:3-management", args: "-p 15672:15672 --name rabbitmq" 

    d.pull_images "cassandra"

    d.run "cassandra", args: "-p 9042:9042 --name cassandra" 
    

  end

end

